apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kumojin-event
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
  - host: kumojin-event.AKS_URL
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kumojin-event
            port:
              number: 80
